name    'loispuig-pagespeed'
version '0.1.0'
source 'git://github.com/loispuig/puppet-phpmyadmin.git'
author 'Loïs PUIG'
license 'MIT'
summary 'Setup phpMyAdmin on Apache web server'
description ''
project_page 'https://github.com/loispuig/puppet-phpmyadmin'
dependency 'puppetlabs/stdlib', '>= 4.12.0 < 5.0.0'
dependency 'puppetlabs/mysql', '>= 3.7.0 < 4.0.0'
dependency 'puppetlabs/apache', '>= 1.9.0'